### ISSUE TITLE
command arguments collapsing

### ISSUE THREAD

**Issue by djbe** [unconed/TermKit#5]
when executing a command with parameters, for example:
`ls -a -l`

we can also write it this way:
`ls -al`

The first one works in TermKit, the second one gives this error:
`ENOENT, No such file or directory '-al'`

Btw, I don't know if argument collapsing is the right name for this 'feature'.

**Comment by unconed** [comment]
The reason this fails is because the "ls" in TermKit is custom (it outputs listings as JSON instead of plaintext). It should work fine for other commands.

I'm hesitant to add the -abc syntax as a general shorthand because it's not universal. Mysql e.g. uses '-pPASSWORD' to specify a password. Of course, the choice is there to only support it for certain commands.

I'll look into this, though it should just be a matter of patching misc.js / parseArgs().

**Comment by Shifty0x88** [comment]
Fix it!  Check out my github @ https://github.com/Shifty0x88/TermKit

Note, I forked from Floby's TermKit so we are going the Linux-way not the Mac-way (sorry unconed i'm not getting a mac anytime soon)

Really it was a change to TermKit/Node/misc.js  / parseArgs() command as unconed suggested.  

May need more testing, but it worked with ls -la.  i just hate typing more then I have to.
