### ISSUE TITLE
Usability enhancements

### ISSUE THREAD

**Issue by nemtsov** [unconed/TermKit#8]
- Tabbing into (with command-tab) TermKit should activate the cursor, so that it's easy to type a command right away. You currently have to (a) tab into TermKit, then (b) click on it with a mouse, and only then (c) start typing the command
- "Ctr-l" should clear the screen;  "Ctr-u" should erase the previous word, etc

**Comment by josephg** [comment]
Also, it should follow normal terminal focus behaviour: When you click anywhere in the window, it should default to focussing the command line.

**Comment by josephg** [comment]
.... Also, up arrow should go to the previous command....

**Comment by phaseq** [comment]
There should also be a way to abort running commands, graphical and by typing Ctrl-c

**Comment by drewish** [comment]
https://github.com/unconed/TermKit/issues/19 has a similar request for Cmd + K.

**Comment by drewish** [comment]
Cmd + T seems to open a new, empty tab resetting the terminal.

**Comment by unconed** [comment]
Re: tab focus. I have full keyboard integration planned. I would not worry about it for now, it is coming soon ;).

Re: up arrow history. Coming soon, with a nice popup, instead of having to guess where you are.

As for clearing the screen and such, I recently implemented a "clear" command. For usability's sake, it would be best if pressing Cmd-K would execute that command in a new line.

Cmd-T is part of the preliminary tabbed terminal support. It opens a new tab, but there is no way to switch between tabs yet.

**Comment by koo5** [comment]
..life?
